# ============================================================
# 📝 FastAPI Student CRUD App - SQLite Database Version
# ============================================================

# ------------------------------------------------------------
# 📦 Import Required Libraries
# ------------------------------------------------------------

# FastAPI framework + error handling + dependency injection
from fastapi import FastAPI, HTTPException, Depends

# For request body validation
from pydantic import BaseModel

# SQLAlchemy database tools
from sqlalchemy import create_engine, Column, Integer, String

# ORM utilities
from sqlalchemy.orm import declarative_base
from sqlalchemy.orm import sessionmaker, Session

# ------------------------------------------------------------
# 🚀 Create FastAPI App
# ------------------------------------------------------------

# Create FastAPI app instance
app = FastAPI()

# ------------------------------------------------------------
# 🗄️ Database Configuration
# ------------------------------------------------------------

# SQLite database file
DATABASE_URL = "sqlite:///./students.db"

# Create database engine
engine = create_engine(
    DATABASE_URL,
    connect_args={"check_same_thread": False}
)

# Create database session
SessionLocal = sessionmaker(bind=engine)

# Base class for database models
Base = declarative_base()

# ------------------------------------------------------------
# 🧱 Database Model (Table)
# ------------------------------------------------------------

# Create students table
class StudentDB(Base):

    # Table name
    __tablename__ = "students"

    # Table columns
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    age = Column(Integer)
    course = Column(String)
    marks = Column(Integer)

# Create table in database
Base.metadata.create_all(bind=engine)

# ------------------------------------------------------------
# 🧾 Pydantic Schema
# ------------------------------------------------------------

# Structure of request/response data
class Student(BaseModel):

    # ID auto-generated by database
    id: int | None = None

    # Student name
    name: str

    # Student age
    age: int

    # Course name
    course: str

    # Marks obtained
    marks: int

    # Convert SQLAlchemy object → JSON
    class Config:
        orm_mode = True

# ------------------------------------------------------------
# 🔌 Dependency (Database Session)
# ------------------------------------------------------------

# Database connection dependency
def get_db():

    # Create database session
    db = SessionLocal()

    try:
        yield db

    finally:

        # Close database connection
        db.close()

# ------------------------------------------------------------
# 🏠 Home Route
# ------------------------------------------------------------

# Home API
@app.get("/")
def home():

    return {"message": "Student CRUD API with Database 🚀"}

# ------------------------------------------------------------
# ✅ 1. Add Student
# POST /students
# ------------------------------------------------------------

@app.post("/students")
def add_student(
    student: Student,
    db: Session = Depends(get_db)
):

    # Create student object
    new_student = StudentDB(

        # Store student name
        name=student.name,

        # Store student age
        age=student.age,

        # Store course name
        course=student.course,

        # Store marks
        marks=student.marks
    )

    # Add student to database
    db.add(new_student)

    # Save changes
    db.commit()

    # Refresh updated object
    db.refresh(new_student)

    # Return success response
    return {
        "message": "Student added successfully",
        "data": new_student
    }

# ------------------------------------------------------------
# ✅ 2. Get All Students
# GET /students
# ------------------------------------------------------------

@app.get("/students")
def get_students(
    db: Session = Depends(get_db)
):

    # Fetch all students from database
    students = db.query(StudentDB).all()

    # Return all student data
    return {
        "count": len(students),
        "data": students
    }

# ------------------------------------------------------------
# ✅ 3. Get Student by ID
# GET /students/{id}
# ------------------------------------------------------------

@app.get("/students/{id}")
def get_student(
    id: int,
    db: Session = Depends(get_db)
):

    # Search student by ID
    student = db.query(StudentDB).filter(
        StudentDB.id == id
    ).first()

    # Check if student exists
    if not student:

        # Raise error if not found
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # Return student data
    return student

# ------------------------------------------------------------
# ✅ 4. Update Student
# PUT /students/{id}
# ------------------------------------------------------------

@app.put("/students/{id}")
def update_student(
    id: int,
    updated_student: Student,
    db: Session = Depends(get_db)
):

    # Find student in database
    student = db.query(StudentDB).filter(
        StudentDB.id == id
    ).first()

    # Check if student exists
    if not student:

        # Raise error if not found
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # Update student name
    student.name = updated_student.name

    # Update student age
    student.age = updated_student.age

    # Update course
    student.course = updated_student.course

    # Update marks
    student.marks = updated_student.marks

    # Save changes
    db.commit()

    # Refresh updated object
    db.refresh(student)

    # Return response
    return {
        "message": "Student updated successfully",
        "data": student
    }

# ------------------------------------------------------------
# ✅ 5. Delete Student
# DELETE /students/{id}
# ------------------------------------------------------------

@app.delete("/students/{id}")
def delete_student(
    id: int,
    db: Session = Depends(get_db)
):

    # Find student by ID
    student = db.query(StudentDB).filter(
        StudentDB.id == id
    ).first()

    # Check if student exists
    if not student:

        # Raise error if not found
        raise HTTPException(
            status_code=404,
            detail="Student not found"
        )

    # Delete student from database
    db.delete(student)

    # Save changes
    db.commit()

    # Return response
    return {
        "message": "Student deleted successfully"
    }